//! Main UCI (uci:) namespace.
//!
//! Common definitions in the namespace.
//! Will also contain sub-namespaces for generated types.
//!

#![allow(dead_code)]
#![warn(missing_docs)]

use std::fmt::{Display, Formatter};

pub mod base;

// ════════════════════════════════════════════════════════════════════════════
// §2  Error types
// ════════════════════════════════════════════════════════════════════════════

/// Classification of error conditions raised by the CAL.
///
/// # CERT coverage
/// CAL-005204, CAL-005369, CAL-016035, CAL-016043, CAL-016050, CAL-016477
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CalErrorKind {
    /// CAL instance failed to initialize (CAL-005204).
    InitializationFailure,
    /// The requested Client Topic is unavailable (CAL-005369).
    TopicUnavailable,
    /// Required platform resources are not available for the operation
    /// (CAL-016043).
    ResourcesUnavailable,
    /// The operation is invalid in the current ASB connection state
    /// (Table 5.9-2).
    InvalidState {
        /// The ASB state when the error occurred.
        current: base::AsbConnectionState,
    },
    /// A UUID supplied to or generated by the CAL does not conform to
    /// RFC 4122 (CAL-016477).
    UuidConformanceError,
    /// The operation is not permitted given the current reader or writer
    /// configuration (CAL-016050 – polling and callback modes are mutually
    /// exclusive).
    OperationNotPermitted,
    /// The ASB has transitioned to the terminal `Failed` state.
    AsbFailed,
    /// The supplied `service_identifier` is invalid or not registered on this
    /// platform.
    InvalidServiceIdentifier,
    /// Serialization or deserialization of a CAL Message failed.
    SerializationError,
    /// Attempted to instantiate an abstract CAL Message or Sub-message type
    /// (CAL-016035).
    AbstractInstantiation,
    /// An internal error within the CAL Implementation.
    ImplementationError{
        /// The optional implementation error type
        kind: Option<CalImplementationErrorKind>},
}

/// More detail on a specific implementation error.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CalImplementationErrorKind {
    /// An error parsing or interpreting the CAL configuration file.
    ConfigError,
    ListenerError,
}

impl Display for CalErrorKind {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::InitializationFailure => write!(f, "CAL initialization failure"),
            Self::TopicUnavailable => write!(f, "Client topic unavailable"),
            Self::ResourcesUnavailable => write!(f, "Required resources unavailable"),
            Self::InvalidState { current } => write!(f, "Operation invalid in state {current}"),
            Self::UuidConformanceError => write!(f, "UUID does not conform to RFC 4122"),
            Self::OperationNotPermitted => write!(f, "Operation not permitted"),
            Self::AsbFailed => write!(f, "Abstract Service Bus has permanently failed"),
            Self::InvalidServiceIdentifier => {
                write!(f, "Invalid or unregistered service identifier")
            }
            Self::SerializationError => write!(f, "CAL Message (de)serialization error"),
            Self::AbstractInstantiation => {
                write!(f, "Cannot instantiate abstract CAL Message type")
            }
            // Implementation errors
            Self::ImplementationError { kind: None } => write!(f, "Internal CAL implementation error"),
            Self::ImplementationError { kind: Some(CalImplementationErrorKind::ConfigError)} => write!(f, "Unable to parse or interpret CAL configuration."),
        }
    }
}

/// The primary error type for all CAL operations.
///
/// Implements [`std::error::Error`] and is [`Send`] + [`Sync`] so it can cross thread
/// boundaries (CAL-016015).
///
/// # CERT coverage
/// CAL-005204, CAL-005369, CAL-016035, CAL-016043, CAL-016050, CAL-016477
///
#[derive(Debug)]
pub struct CalError {
    /// Error classification.
    pub kind: CalErrorKind,
    /// Human-readable description.
    pub message: String,
    /// Optional causal chain.
    pub source: Option<Box<dyn std::error::Error + Send + Sync + 'static>>,
}

impl CalError {
    /// Construct a new [`CalError`] with no causal source.
    pub fn new(kind: CalErrorKind, message: impl Into<String>) -> Self {
        Self {
            kind,
            message: message.into(),
            source: None,
        }
    }

    /// Construct a new [`CalError`] wrapping an existing error as its cause.
    pub fn with_source(
        kind: CalErrorKind,
        message: impl Into<String>,
        source: impl std::error::Error + Send + Sync + 'static,
    ) -> Self {
        Self {
            kind,
            message: message.into(),
            source: Some(Box::new(source)),
        }
    }

    /// Constructs a new [`CalError`] with kind [`CalErrorKind::ImplementationError`]
    pub fn new_impl(kind: CalImplementationErrorKind, message: impl Into<String>) -> Self {
        Self {
            kind: CalErrorKind::ImplementationError { kind: Some(kind) },
            message: message.into(),
            source: None,
        }
    }

    /// Constructs a new [`CalError`] with kind [`CalErrorKind::ImplementationError`] wrapping an existing error as its cause.
    pub fn with_impl_source(
        kind: CalImplementationErrorKind,
        message: impl Into<String>,
        source: impl std::error::Error + Send + Sync + 'static,
    ) -> Self {
        Self {
            kind: CalErrorKind::ImplementationError { kind: Some(kind) },
            message: message.into(),
            source: Some(Box::new(source)),
        }
    }
}

impl Display for CalError {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self.source {
            Some(ref src) => write!(f, "{}: {}\nFrom: {}", self.kind, self.message, src),
            None => write!(f, "{}: {}", self.kind, self.message),
        }
    }
}

impl std::error::Error for CalError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.source
            .as_deref()
            .map(|s| s as &(dyn std::error::Error + 'static))
    }
}

/// Convenience [`Result`] alias for all fallible CAL operations.
pub type CalResult<T> = Result<T, CalError>;
