[package]
name = "rcal_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[[test]]
name = "integration"
harness = true

[dev-dependencies]
slog = "2.8.2"
slog-term = "2.9.2"
slog-async = "2.8.0"
rcal = { path = ".." }
tokio = { version = "1.53.1", features = ["full"] }
