[package]
name = "cal-bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
chrono = "0.4"
clap = { version = "4.6.6", features = ["derive"] }
rcal = { version = "2", path = "../rcal" }
rcal_macros = { version = "2.0.0", path = "../rcal/rcal_macros" }
slog = "2"
tokio = { version = "1", features = ["full"] }
