[workspace]
members = ["rcal_macros", "xsd-subset", "examples/simple_two_service"]

[workspace.package]
version = "1.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tclarke/rcal"

[package]
name = "rcal"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "OMS Critical Abstraction Layer (CAL) implementation for Rust"

[features]
service = []
default = ["service"]

[dependencies]
lazy_static = "1.5.0"
regex = "1"
mac_address = { version = "1.1.8", features = ["serde"] }
rcal_macros = { path = "./rcal_macros", version = "1.0.0" }
serde = { version = "1.0.229", features = ["derive"] }
slog = "2.8.2"
slog-async = "2.8.0"
slog-json = "2.6.1"
slog-term = "2.9.2"
toml = "1.1.4"
uuid = { version = "1.24.0", features = ["v1", "v3", "v4", "slog", "serde", "rng"] }
omq-tokio = { version = "0.21.1", optional = true }
tokio = { version = "1.53.1", features = ["full"] }
quick-xml = { version = "0.37", features = ["serialize"] }
chrono = { version = "0.4.45", features = ["serde"] }

[features]
zmq = ["dep:omq-tokio"]
default = ["zmq"]

[build-dependencies]
quick-xml = { version = "0.37" }
glob = "0.3.4"

[[bin]]
name = "zmq_peer_sender"
required-features = ["zmq"]

[[example]]
name = "system_status"

[[example]]
name = "basic"

[[example]]
name = "custom_tokio"

[[test]]
name = "zmq_radio_dish"
harness = true
required-features = ["zmq"]

[[test]]
name = "zmq_asb_system"
harness = true
required-features = ["zmq"]

[[test]]
name = "zmq_qos"
harness = true
required-features = ["zmq"]

[dev-dependencies]
serde_json = "1.0.151"

[workspace.metadata.release]
allow-branch = [ "main" ]
sign-commit = true
sign-tag = true
publish = false
verify = false
