name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  clippy:
    name: Run clippy on workspace
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: rcal

      - name: Install required cargo
        run: cargo install clippy-sarif sarif-fmt

      - name: Run Clippy
        run:
          cargo clippy
          --all-targets
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true
        working-directory: rcal
        env:
          RCAL_XSD_PATH: examples/UCI_SystemStatusOnly_v2_5_0.xsd

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: rcal/rust-clippy-results.sarif
          wait-for-processing: true
  test:
    name: Run all unit and integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: rcal
      - run: cargo test
        working-directory: rcal
        env:
          RCAL_XSD_PATH: examples/UCI_SystemStatusOnly_v2_5_0.xsd
  examples:
    name: Build and run examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: rcal
      - run: cargo run --example system_status
        working-directory: rcal
        env:
          RCAL_XSD_PATH: examples/UCI_SystemStatusOnly_v2_5_0.xsd
